export const actionType = {
    CART_ADD_ITEM: 'CART_ADD_ITEM',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
    ADD_SHIPPING_ADDRESS: 'ADD_SHIPPING_ADDRESS',
    SELECT_PAYMENT_METHOD: 'SELECT_PAYMENT_METHOD',
}