export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const ADD_SHIPPING_ADDRESS = 'ADD_SHIPPING_ADDRESS';
export const SELECT_PAYMENT_METHOD = 'SELECT_PAYMENT_METHOD';