const authActionTypes = {
    // login
    USER_LOGIN_LOADING: "USER_LOGIN_LOADING",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
    // signup
    USER_SIGNUP_LOADING: "USER_SIGNUP_LOADING",
    USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
    USER_SIGNUP_FAIL: "USER_SIGNUP_FAIL",
}
export default authActionTypes